#!/usr/bin/env python3
"""Generate a compact GBK lead/trail -> Unicode lookup for txt-reader."""
from __future__ import annotations

import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "txt-reader", "main", "gbk_table.c")

# GBK: lead 0x81..0xFE, trail 0x40..0x7E and 0x80..0xFE
LEAD_BASE = 0x81
LEAD_COUNT = 0xFE - 0x81 + 1  # 126
TRAIL_BASE = 0x40
TRAIL_COUNT = 0xFE - 0x40 + 1  # 191 (includes 0x7F hole)


def main():
    table = [[0] * TRAIL_COUNT for _ in range(LEAD_COUNT)]
    mapped = 0
    for lead in range(0x81, 0xFF):
        for trail in range(0x40, 0xFF):
            if trail == 0x7F:
                continue
            try:
                ch = bytes([lead, trail]).decode("gbk")
            except UnicodeDecodeError:
                continue
            if len(ch) != 1:
                continue
            code = ord(ch)
            if code > 0xFFFF:
                continue
            table[lead - LEAD_BASE][trail - TRAIL_BASE] = code
            mapped += 1

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("#include <stdint.h>\n\n")
        f.write(f"// Generated by tools/gen_gbk_table.py — {mapped} mappings\n")
        f.write(f"#define GBK_LEAD_BASE   0x{LEAD_BASE:02X}\n")
        f.write(f"#define GBK_LEAD_COUNT  {LEAD_COUNT}\n")
        f.write(f"#define GBK_TRAIL_BASE  0x{TRAIL_BASE:02X}\n")
        f.write(f"#define GBK_TRAIL_COUNT {TRAIL_COUNT}\n\n")
        f.write(f"const uint16_t gbk_unicode[{LEAD_COUNT}][{TRAIL_COUNT}] = {{\n")
        for row in table:
            f.write("    {")
            f.write(", ".join(f"0x{v:04X}" for v in row))
            f.write("},\n")
        f.write("};\n")
    print(f"Wrote {OUT}, mappings={mapped}, bytes~={LEAD_COUNT * TRAIL_COUNT * 2}")


if __name__ == "__main__":
    main()
